### ISSUE TITLE
Error file config not found

### ISSUE THREAD

**Issue by ngankilo** [wshihadeh/docker-deployment-action#7]
Hi Brothers,
First of all thanks for your work here.
I'm using the following configuration for my action

```
name: Node.js CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: copy env 
      run: cp .env.example .env
    - name: Deploy to Docker
      uses: wshihadeh/docker-deployment-action@master
      with:
        remote_docker_host: ${{ secrets.USER }}@${{ secrets.HOST }}
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        deployment_mode: docker-compose
        deploy_path: /home/ubuntu/deployment-test
        stack_file_name: docker-compose.yml
        args: up -d
```

But, when Action build, I have got the error like this,

```/usr/bin/docker run --name b3ac6c296aa77a11840cfafcbc8cbaaffda9a_141ad3 --label 3b3ac6 --workdir /github/workspace --rm -e INPUT_REMOTE_DOCKER_HOST -e INPUT_SSH_PRIVATE_KEY -e INPUT_SSH_PUBLIC_KEY -e INPUT_DEPLOYMENT_MODE -e INPUT_DEPLOY_PATH -e INPUT_STACK_FILE_NAME -e INPUT_ARGS -e INPUT_COPY_STACK_FILE -e INPUT_KEEP_FILES -e INPUT_DOCKER_PRUNE -e INPUT_PRE_DEPLOYMENT_COMMAND_ARGS -e INPUT_PULL_IMAGES_FIRST -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/API/API":"/github/workspace" 3b3ac6:c296aa77a11840cfafcbc8cbaaffda9a up -d
Registering SSH keys...
Identity added: /github/home/.ssh/id_rsa (/github/home/.ssh/id_rsa)
Agent pid 10
Add known hosts
Connecting to ***@***... Command: docker-compose  --log-level debug --host ssh://***@*** -f docker-compose.yml up -d
Using configuration files: ./docker-compose.yml
Trying paths: ['/github/home/.docker/config.json', '/github/home/.dockercfg']
No config file found
Trying paths: ['/github/home/.docker/config.json', '/github/home/.dockercfg']
No config file found
/usr/lib/python3.8/site-packages/paramiko/client.py:835: UserWarning: Unknown ssh-ed25519 host key for ***: b'5aaac58e6cdc4c3943ff4f82a3229964'
  warnings.warn(
Traceback (most recent call last):
File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.4', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 125, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3.8/site-packages/compose/cli/command.py", line 54, in project_from_options
    return get_project(
  File "/usr/lib/python3.8/site-packages/compose/cli/command.py", line 147, in get_project
    client = get_client(
  File "/usr/lib/python3.8/site-packages/compose/cli/command.py", line 118, in get_client
    client = docker_client(
  File "/usr/lib/python3.8/site-packages/compose/cli/docker_client.py", line 127, in docker_client
    client = APIClient(**kwargs)
  File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 165, in __init__
    self._custom_adapter = SSHHTTPAdapter(
  File "/usr/lib/python3.8/site-packages/docker/transport/sshconn.py", line 111, in __init__
    self._connect()
  File "/usr/lib/python3.8/site-packages/docker/transport/sshconn.py", line 119, in _connect
    self.ssh_client.connect(**self.ssh_params)
  File "/usr/lib/python3.8/site-packages/paramiko/client.py", line 435, in connect
    self._auth(
  File "/usr/lib/python3.8/site-packages/paramiko/client.py", line 764, in _auth
    raise saved_exception
  File "/usr/lib/python3.8/site-packages/paramiko/client.py", line 740, in _auth
    self._transport.auth_publickey(username, key)
  File "/usr/lib/python3.8/site-packages/paramiko/transport.py", line 1580, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/lib/python3.8/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```
I don't have any idea to fix its. So could you please support to me??
Thanks and Best Regard.

**Comment by wshihadeh** [comment]
From the attached repo it seems that you are  using the wrong ssh configurations 
```
Unknown ssh-ed25519 host key for ***
```
double-check the ssh secrets and make sure that you are using the correct values

**Comment by ngankilo** [comment]
> From the attached repo it seems that you are using the wrong ssh configurations
> 
> ```
> Unknown ssh-ed25519 host key for ***
> ```
> 
> double-check the ssh secrets and make sure that you are using the correct values

Thanks for your response, I have fixed it.

**Comment by jreh99** [comment]
> > From the attached repo it seems that you are using the wrong ssh configurations
> > ```
> > Unknown ssh-ed25519 host key for ***
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > double-check the ssh secrets and make sure that you are using the correct values
> 
> Thanks for your response, I have fixed it.

How did you fix it? 
What does your public key format look like?

**Comment by 1zilc** [comment]
The same problem

**Comment by leaniosci** [comment]
from the readme 
```
Remote Docker SSH public key.

Do not give the content of id_rsa.pub

The content of ~/.ssh/known_hosts needs to be given here. You can get it by connecting to host once using your own machine. Example:

1.1.1.1 ecdsa-sha2-nistp256 AAAAE2VjZHNhLNTYAAAAIbmlzdHAyNCN5F3TLxUllpSRx8y+9C2uh+lWZDFmAsFMjcz2Zgq4d5F+oGicGaRk=

```
